# Sample workflow for building and deploying a Next.js site to GitHub Pages
#
# To get started with Next.js see: https://nextjs.org/docs/getting-started
#
name: Deploy Vite site to Pages

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      # configure-pages step removed due to intermittent TypeError in the action

      - name: Restore cache
        uses: actions/cache@v4
        with:
          path: |
            web/node_modules
            ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('web/**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install dependencies
        run: |
          cd web
          npm i

      - name: Build (Vite)
        run: |
          cd web
          npm run build

      - name: Verify build output
        run: |
          if [ ! -d web/dist ]; then
            echo "Build output directory web/dist not found. Vite build may have failed." >&2
            echo "Run 'cd web && npm run build' locally to inspect errors." >&2
            exit 1
          fi
          echo "web/dist contents:" && ls -la web/dist

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./web/dist

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
